### ISSUE TITLE
Visual Bug: Inventories can appear empty when dropping an inventory to pick up another

### ISSUE THREAD

**Issue by CompilerErrorRBX** [CompilerErrorRBX/Quarantine-Aftermath#22] opened 2024-02-05 17:35 UTC
https://medal.tv/games/roblox/clips/1T5aX1YFC6iB0F/6p6KQxSislSD?invite=cr-MSxLOXMsMTk5OTU3MTY3LA?mobilebypass=true

**Comment by DarrenLam2** [comment] 2024-02-14 23:27
https://streamable.com/w9pmb4

Turns out, this is a whole string of bugs that causes a bunch of funny stuff to happen. This is all likely because of 1 root cause, but I am not a developer so I wouldn't know. I am going to list all bugs in 1 post because of the reason that they are all likely stemming from the same root problem. 

This bug revolves around 1 primary item: glitched containers. I will be describing backpacks, but this will likely work for every container. 

# Reproduce glitched backpack (weight method)
1: Have 2 backpacks
2: Have one backpack with a lower remaining weight than the second backpack and all the contents within the second backpack. 
3: Try to pick up the other backpack from the ground in any way you want (E, equip, take). It will glitch the backpack on the ground.
4: If you wear a glitched backpack and try to pick up a normal backpack, it will also glitch the previously normal backpack. 

# Glitched Backpack details
The glitched backpack has no visible slots, despite being equipped. Upon scrapping or destroying, all previous contents in the bag will be destroyed, regardless of where you scrap the bag (on your character, or on the ground). Rejoining with a glitched bag will delete all contents, but will fix the fact that there is no inventory container. 

#The Rabbit Hole (Other related bugs)
## Extra backpack panel (non-functional)
1: 2 backpacks: 1 larger 1 smaller
2: Have smaller backpack inside larger backpack inventory
3: Fill large backpack inventory past the capacity of the smaller backpack
4: Keep swapping between both
5: Sometimes, you will get another backpack in your inventory.

## Details
There seems to be no way of getting rid of that slot. Resetting does not even reset that panel. You must rejoin. The extra backpack is non-functional.

## Extra backpack panel + exceed weight limit (both visual)
Same reproduce method as before
https://streamable.com/2q8p8k

Not so sure what causes any of these bugs, but I am really unsure about why the extra weight happens specifically. When you update the glitched stack (by splitting, transferring to another stack, etc.) it will update correctly. This may only work with biofuel, since it is a quantity based item that has a durability bar, but I am not sure. 

What I have found to be the most consistent way to replicate these bugs is to use all of 1 specific item. Put the backpack in the first slot, and going from left to right, top to bottom, put the biofuel in order. Put the non-full stack either in the second slot or last slot. It may be possible to do with multiple items. 

## Extra backpack panel + glitched items
I'm not even going to bother giving descriptions for these anymore. Just watch the clips.

## Glitched backpacks (slots method)
Set up similar to weight method, but you fill the backpack up. You pick up the other backpack, and it glitches. If you empty a slot and pick the backpack back up, reequipping the backpacks several times will cause backpacks to eventually overlap equips, and glitch both backpacks out. 
https://streamable.com/3jdcfw

There are more bugs that revolve around this for sure, but these are the ones that I can find some sort of consistent replication for so far.

**Comment by DarrenLam2** [comment] 2024-02-17 16:53
Seems to be fixed.

**Closed** 2024-02-27 20:32 UTC
Labels: bug
